initial configuration of the java training
wolox-training/jcp-java pull request #1
Opened 2021-09-24 20:15 UTC by JuanPoliWolox

**Summary**
- Completed the project setup
- Finished PR structure

**Trello Card**
 - https://trello.com/c/EvnUQ5XE/42-pull-request

**Screenshots**

![gifStructureSpring](https://user-images.githubusercontent.com/72398051/134734270-d8fbc2cb-674d-401c-a74d-c489f80ee94a.gif)

2021-09-27 17:09 UTC, juandbc requested changes

2021-09-27 17:09 UTC, juandbc commented on build.gradle
> +sourceCompatibility = '8'
Here we should use the constants values offer by Gradle API. Also like **optional**, you can specify the target compatibility
```suggestion
sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8
```

2021-09-27 17:09 UTC, juandbc commented on src/main/resources/application.properties
> +spring.datasource.password=wolox2021
Just as a **reminder**, we should not leave credentials in the property files for the production environment. In this case, it is fine. No need to change it

2021-09-27 19:16 UTC, juandbc approved these changes

2021-10-06 13:11 UTC, torsello approved these changes
LGTM!

2021-10-06 13:48 UTC, merged