Guava checkNotNull to setters added
wolox-training/jcp-java pull request #6
Opened 2021-10-14 12:49 UTC by JuanPoliWolox

**Summary**

- checkNotNull precondition added to all setters methods

**Trello Cards**

- https://trello.com/c/qb9CggYd/29-agregar-validaci%C3%B3n-de-precondiciones-a-los-setters

**Screenshots**

<img width="760" alt="Captura de Pantalla 2021-10-14 a la(s) 09 47 57" src="https://user-images.githubusercontent.com/72398051/137320355-30f6b42c-bae0-4266-bed5-e32ea347bc46.png">

2021-10-20 02:41 UTC, juandbc requested changes

2021-10-20 02:41 UTC, juandbc commented on src/main/java/wolox/training/constants/ErrorConstants.java
> +    public static final String nullMessage = "Please check the Object supplied, its null!";
This message can be improved. The word ** object ** can be replaced with a placeholder which is then replaced with the name of the field using `String.format()`.

2021-10-20 02:41 UTC, juandbc commented on src/main/java/wolox/training/models/Book.java
> +        Preconditions.checkNotNull(bookGenre, nullMessage);
This is not a required field
```suggestion
```

2021-10-20 02:41 UTC, juandbc commented on src/main/java/wolox/training/models/User.java
> +        Preconditions.checkNotNull(userBirthday, nullMessage);
This is not a required field
```suggestion
```

2021-10-22 15:22 UTC, juandbc approved these changes

2021-10-26 17:10 UTC, torsello approved these changes
LGTM

2023-02-10 12:56 UTC, closed without merging