UserController tests added
wolox-training/jcp-java pull request #7
Opened 2021-10-15 12:52 UTC by JuanPoliWolox

**Summary**

- UserControlerTest class added
- gradle.build dependencies upgraded for download problems

**Trello Cards**

- https://trello.com/c/L06A2wM7/28-junit-testing

**Screenshots**
![junitTestsgif](https://user-images.githubusercontent.com/72398051/137489584-2401d422-dc5c-4b78-be87-f0c9bead12f2.gif)

2021-10-20 03:08 UTC, juandbc requested changes
The tests for the model layer using the `DataJpaTest` annotation are missing

2021-10-20 03:08 UTC, juandbc commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-web:2.5.5'
You can handle the version in one place at the spring boot plugin. This is a suggestion, no need to apply the change🙂

2021-10-20 03:08 UTC, juandbc commented on src/test/java/wolox/training/controllers/UserControllerTest.java
> +    private UserController userController;
This is not necessary, the `WebMvcTest` annotation creates a context with an instance of` UserController`.
Also keep this in mind for the future: the class you want to test should not be mocked, only external resources such as a database, web services, should be mocked because you have no control over them.
```suggestion
```

2021-10-20 03:08 UTC, juandbc commented on src/test/java/wolox/training/controllers/UserControllerTest.java
> +                .andExpect(status().isOk());
The mocks for `userRepository` in the tests are missing. For example:
```suggestion
        doReturn(users).when(userRepository).findAll();
        mvc.perform(MockMvcRequestBuilders.get("/users").contentType(MediaType.APPLICATION_JSON_VALUE))
                .andExpect(status().isOk());
```

2021-10-20 03:08 UTC, juandbc commented on src/test/java/wolox/training/controllers/UserControllerTest.java
> +    public void givenAUser_whenPostAUser_thenReturnCreatedStatusCode() throws Exception {
These all are tests for a happy path, it would be good to have tests for a sad path like bad request or not found

2021-11-02 16:49 UTC, juandbc approved these changes

2021-12-23 19:44 UTC, torsello approved these changes

2023-02-10 12:57 UTC, closed without merging